### ISSUE TITLE
make menuconfig says i dont have ncurses installed and devel version but i do

### ISSUE THREAD

**Issue by Rioboyva2554** [linux-3ds/buildroot#10]
Im on fedora and i was trying to compile build root from the source file you gave me so i did what it said and ran make menuconfig but error i check my downloads its installed i then reinstall ncurses and the devel version error i then run make defconfig works but when i run the menuconfig still error

PKG_CONFIG_PATH="" make CC="/usr/lib64/ccache/gcc" HOSTCC="/usr/lib64/ccache/gcc" \
    obj=/home/rio/Downloads/buildroot-latest/output/build/buildroot-config -C support/kconfig -f Makefile.br mconf
make[1]: Entering directory '/home/rio/Downloads/buildroot-latest/support/kconfig'
 *** Unable to find the ncurses libraries or the
 *** required header files.
 *** 'make menuconfig' requires the ncurses libraries.
 *** 
 *** Install ncurses (ncurses-devel or libncurses-dev 
 *** depending on your distribution) and try again.
 *** 
make[1]: *** [Makefile:253: /home/rio/Downloads/buildroot-latest/output/build/buildroot-config/dochecklxdialog] Error 1
make[1]: Leaving directory '/home/rio/Downloads/buildroot-latest/support/kconfig'
make: *** [Makefile:961: /home/rio/Downloads/buildroot-latest/output/build/buildroot-config/mconf] Error 2

**Comment by kleo** [comment]
you can follow https://github.com/linux-3ds/buildroot/blob/master/.github/workflows/build.yml for building

**Comment by ParzivalWolfram** [comment]
You'll want to use `make nconfig` for now, this version of Buildroot seems to have issues detecting the newer versions of ncurses properly sometimes.
